name: laravel_rest_api_flutter
description: A generic Dart/Flutter wrapper to consume Laravel REST APIs - search, mutate, delete and trigger backend actions
version: 0.2.2
homepage: https://github.com/xefi/laravel-rest-api-flutter

environment:
  sdk: ^3.10.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.5
  build_runner: ^2.2.0

flutter:
